### ISSUE TITLE
Presentation for OLA Sept 28 community convening

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/DCOLA#1]
Create data visuals for State of Latinos in DC presentation at OLA Sept 28 community convening.

**Comment by ptatian** [comment]
@sdiby: Calculating 2000 unemployment rates from the NCDB (Ncdb.Ncdb_lf_2000_dc) is a little complicated. But, here’s how you do it.

For the total population, it is `100 * UNEMPT0N / UNEMPT0D`

For population by race it is, `100 * ( rMUNEMP0 + rFUNEMP0 ) / (rMUNEMP0 + rMEMP0 + rFUNEMP0 + rFEMP0 )`

where r = W for white, X for non-Hispanic white, B for black, H for Hispanic/Latino, I for American Indian, A for Asian/Native Hawaiian/Pacific Islander, O for other race. 

Also, please note that Ncdb.Ncdb_lf_2000_dc is a **tract-level data set**, so you need to sum all of the observations to get the city total.

**Comment by ptatian** [comment]
@sdiby: I seem to have the code working now. I pushed some commits that you should sync to your local repository.

Initially, the problem was with the variables listed for the **moe_vars** macro variable in Macros\DCOLA_ACS_summary_geo.sas. You can't have any margin of error variables in this list that aren't created in the final data set, so that was causing a fatal error. Once I replaced the list, I fixed a few other minor problems of missing semicolons and missing commas between variables in the sum() function.

Another issue was that you needed to have batch submitted the new ACS program (Acs_sf_2010_14_dc.sas) on L: to create the new permanent data sets that these programs need. Otherwise, you would get uninitialized variables because the needed table cells weren't in the current data set. 

You should try running yourself and see if this looks OK.

**Comment by ptatian** [comment]
Also, in Compile_data_DCOLA.sas, you needed to include all of the libraries referenced in the program as %DCData() calls at the start. 

> %DCData_lib( DCOLA )
> %DCData_lib( ACS )
> %DCData_lib( Equity )
> %DCData_lib( NCDB )

**Comment by ptatian** [comment]
Hi @sdiby and @chedman,

I'm just reviewing some old GitHub issues and noticing that this one was never closed. Do either of you have any uncommitted or unsynced changes for this repository? 

Peter

**Comment by chedman** [comment]
Hi @ptatian @sdiby,

Hmm... I don't remember this thread and not sure how/why I jumped on, but it looks like I did at one point. As far as I can tell I don't have any committed changes to this repository. 

thanks,
Carl

**Comment by ptatian** [comment]
@sdiby Would you please check whether you have any uncommitted changes to the DCOLA repository in branch develop-#1? After committing any remaining changes, we should probably merge and close this branch. Thank you.

**Comment by sdiby** [comment]
Hi @ptatian ,
All changes have been committed and I've merged and closed the branch.

Thank you,
Somala

**Comment by ptatian** [comment]
OK, thank you!
