### ISSUE TITLE
Revise DC SOI report populations

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/DCOLA#13]

**Comment by ptatian** [comment]
@maggiesu0725 As I noted in my email, I would like you to update the IPUMS data tables we created to reflect the population choices made by the respective mayor's offices. There are two main programs involved. In this issue, you will update the main data set that is used to produce the tables. This data set is created by the program **Prog\SOIAA2018\Ipums_SOIAA_2018.sas**.  

The first step in the population selection is to divide the countries into groups using a format:

```
proc format;
  value bpld_a
    00100-12092, 71040-71050, 90000-90022 = 'US & territories'
    15000-19900, 29900, 29999 = 'Canada & other North America'
    20000       = 'Mexico'
    21000-21090 = 'Central America'
    25000-26095 = 'Caribbean'
    30000-30091 = 'South America'
    40000-49900 = 'Europe'
    50000-59900 = 'Asia'
    71000-71039 = 'Pacific Islands'
    60000-60099 = 'Africa'
    70000-70020 = 'Australia & New Zealand'
    71090, 80000-80050 = 'Other non-US'
    95000-99900, . = 'Missing';
run;
```

You'll want to edit the above so that the populations we want to exclude are separated from those we want to include. I would add the excluded countries to the 'Other non-US' category. But, you also need to remove them from the country group they are currently in because you cannot have repeated values on the left side of the equal sign for a format. 

That should be all that is needed to make the changes. You can test this out and, when it's ready, ask @rpitingolo or @lhendey to review, merge, sync, and batch submit on L:. 

When that is done, you can proceed to issue #14 (which I still need to write).

**Comment by maggiesu0725** [comment]
@ptatian I checked the program and made sure I put puerto rico in central america category so they can be included in the Latino immigrants country of origin, but it is not showing up in the populated tables. Couldn't identify what to change in the tables_ipums_SUIAA_2018 either. I will stop making tables for Latinos until this is resolved.
cc. @rpitingolo

**Comment by ptatian** [comment]
@maggiesu0725 OK, I'll take a look. @rpitingolo

**Comment by ptatian** [comment]
@maggiesu0725 @rpitingolo Work on this issue was completed, so this issue should have been closed. I'll continue the follow up with issue #17.
