### ISSUE TITLE
Create revised SOI report tables

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/DCOLA#14]

**Comment by ptatian** [comment]
Needs #13 to be completed first. 

@maggiesu0725 In this issue you'll recreate the IPUMS data tables for the SOI report. Tables are created by the **Prog\SOIAA2018\Tables_ipums_SOIAA_2018.sas** program, but there's one modification you need to make. 

One of the country labels includes a reference to a former country that we want to remove. The country labels currently aren't in the table program. We are using the default IPUMS format for those. So, you'll need to copy that code and add it to the Proc Format in the **Tables_ipums_SOIAA_2018.sas** program. 

The format is called _bpld_f_ and its definition can be found in **L:\Libraries\IPUMS\Prog\Ipums_formats_2011_15.sas**. Simply copy the entire `value BPLD_f ... ;` statement of the Proc Format code from this program to the Proc Format in **Tables_ipums_SOIAA_2018.sas**. Then, you should edit the copied code to change the following label from 

```
  60012 = "Egypt/United Arab Rep."
```
to 
```
  60012 = "Egypt"
```

This should be the only change required. 

You should then be able to rerun all of the tables, which will be output as RTF files in the **Prog\SOIAA2018** folder. These data can then be used to create the updated charts. 

I hope that's clear. Let me know if you have any questions.

**Comment by maggiesu0725** [comment]
@ptatian  should value bpld_a (notsorted) ... also be updated to the country of origin each office has agreed on? or update-#13 should fix it? 
cc @rpitingolo

**Comment by ptatian** [comment]
@maggiesu0725 No, I don’t think bpld_a should be changed. That one is purely geographic and is not used to select populations for the different tables. It is just used to summarize actual place of origin. If that doesn’t make sense, please let me know. Thanks. Cc: @rpitingolo

**Comment by ptatian** [comment]
@maggiesu0725 @rpitingolo Work on this issue was completed, so this issue should have been closed. I'll continue the follow up with issue #17.
